name: Doxygen docs

on:
  push:
    branches: [ main ]

jobs:
  sync:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@v1.9.5

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
